import { useMemo, useState } from 'react'
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Funnel, FunnelChart, LabelList, Legend, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { CustomSelect, Card, PageHeader } from '../components/ui'
import { useAppStore } from '../stores/useAppStore'
import { breachRisk, daysWaiting } from '../utils/domain'

const allVolume=[{m:'Mar',v:2080},{m:'Apr',v:2230},{m:'May',v:2180},{m:'Jun',v:2360},{m:'Jul',v:2410},{m:'Aug',v:2310}],colors=['#3346A8','#19A7AE','#7C4DFF','#F59E0B','#E45858','#64748B']
export default function Analytics(){
  const s=useAppStore();const[period,setPeriod]=useState('Last 30 days');const factor=period==='Last quarter'?1:period==='Last 7 days'?.25:.55
  const volume=useMemo(()=>allVolume.slice(period==='Last 7 days'?-2:period==='Last 30 days'?-3:0).map(x=>({...x,v:Math.round(x.v*factor)})),[period,factor])
  const funnel=[{name:'Received',value:1240},{name:'Processed',value:1186},{name:'Complete',value:913},{name:'Approved',value:842},{name:'Waiting',value:698},{name:'Scheduled',value:486},{name:'Attended',value:371}].map(x=>({...x,value:Math.round(x.value*factor)}))
  const specialty=Object.entries(s.waitingList.reduce<Record<string,number>>((a,w)=>(a[w.specialty]=(a[w.specialty]||0)+1,a),{})).map(([name,value])=>({name,value}))
  const duration=[{name:'0–14 days',value:s.waitingList.filter(w=>daysWaiting(w.waitingSince)<=14).length},{name:'15–28 days',value:s.waitingList.filter(w=>daysWaiting(w.waitingSince)>14&&daysWaiting(w.waitingSince)<=28).length},{name:'29–42 days',value:s.waitingList.filter(w=>daysWaiting(w.waitingSince)>28&&daysWaiting(w.waitingSince)<=42).length},{name:'43+ days',value:s.waitingList.filter(w=>daysWaiting(w.waitingSince)>42).length}]
  const priority=['Routine','Priority','Urgent','Very Urgent'].map(name=>({name,value:s.waitingList.filter(w=>w.priority===name).length}))
  const operational=[{name:'Breach risk',value:s.waitingList.filter(w=>['High','Breached'].includes(breachRisk(w))).length},{name:'Incomplete referrals',value:s.referrals.filter(r=>r.readiness==='Incomplete').length},{name:'Cancellation-ready',value:s.waitingList.filter(w=>w.cancellationReady&&w.status==='Active').length}]
  return <><PageHeader title="Access Analytics" subtitle="Track referral quality, waiting performance, scheduling effectiveness and attendance outcomes." actions={<CustomSelect aria-label="Analytics date range" value={period} onChange={e=>setPeriod(e.target.value)}><option>Last 7 days</option><option>Last 30 days</option><option>Last quarter</option></CustomSelect>}/>
    <div className="capacity-kpis">{[['Referral volume',funnel[0].value.toLocaleString(),'+4.7%'],['Completion rate','73.6%','+2.1 pts'],['Average validation','7.4 hrs','-48 min'],['Average wait','43 days','-3 days'],['Breach rate','13.1%','-1.2 pts'],['Cancellation fill','78.4%','+6.8 pts'],['No-show rate','6.2%','-0.6 pts'],['Utilisation','84.2%','+3.1 pts'],['Missing information',s.referrals.filter(r=>r.readiness==='Incomplete').length.toString(),'Live demo records']].map(x=><Card key={x[0]}><span>{x[0]}</span><strong>{x[1]}</strong><small>{x[2]}</small></Card>)}</div>
    <div className="analytics-grid"><Card title={`Referral volume · ${period}`}><ResponsiveContainer width="100%" height={280}><AreaChart data={volume}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="m"/><YAxis/><Tooltip/><Area dataKey="v" stroke="#3346A8" fill="#EEF1FF" strokeWidth={2}/></AreaChart></ResponsiveContainer></Card><Card title="Waiting by specialty"><ResponsiveContainer width="100%" height={280}><PieChart><Pie data={specialty} dataKey="value" nameKey="name" innerRadius={60} outerRadius={90}>{specialty.map((_,i)=><Cell key={i} fill={colors[i%colors.length]}/>)}</Pie><Tooltip/><Legend/></PieChart></ResponsiveContainer></Card></div>
    <div className="analytics-grid"><Card title="Waiting duration"><ResponsiveContainer width="100%" height={260}><BarChart data={duration}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name"/><YAxis allowDecimals={false}/><Tooltip/><Bar dataKey="value" fill="#19A7AE"/></BarChart></ResponsiveContainer></Card><Card title="Priority distribution"><ResponsiveContainer width="100%" height={260}><PieChart><Pie data={priority} dataKey="value" nameKey="name" outerRadius={90}>{priority.map((_,i)=><Cell key={i} fill={colors[i]}/>)}</Pie><Tooltip/><Legend/></PieChart></ResponsiveContainer></Card></div>
    <Card className="analytics-section-card" title="Waiting-list operational risks"><ResponsiveContainer width="100%" height={260}><BarChart data={operational} layout="vertical"><CartesianGrid strokeDasharray="3 3" horizontal={false}/><XAxis type="number" allowDecimals={false}/><YAxis dataKey="name" type="category" width={140}/><Tooltip/><Bar dataKey="value" fill="#E45858" radius={[0,4,4,0]}/></BarChart></ResponsiveContainer></Card>
    <Card className="analytics-section-card funnel-card" title="Referral-to-attendance funnel"><div className="funnel-chart-frame"><ResponsiveContainer width="100%" height={330}><FunnelChart margin={{top:8,right:130,bottom:8,left:18}}><Tooltip/><Funnel dataKey="value" data={funnel}><LabelList position="right" fill="#182337" stroke="none" dataKey="name"/></Funnel></FunnelChart></ResponsiveContainer></div></Card>
  </>
}
