import { useMemo, useState } from 'react'
import { AlertTriangle, Sparkles } from 'lucide-react'
import { Bar, BarChart, CartesianGrid, Legend, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { Badge, Card, PageHeader } from '../components/ui'
import { useAppStore } from '../stores/useAppStore'

type View='By Specialty'|'By Clinician'|'By Location'|'By Week'
const base=[{specialty:'Cardiology',clinician:'Dr. Sarah Wilson',location:'North Wing',week:'10 Aug',waiting:1420,slots:840,utilisation:92},{specialty:'Orthopaedics',clinician:'Dr. Helen Moore',location:'Central Outpatients',week:'10 Aug',waiting:980,slots:720,utilisation:88},{specialty:'Neurology',clinician:'Dr. Louise Chen',location:'East Wing',week:'17 Aug',waiting:640,slots:590,utilisation:84},{specialty:'Respiratory',clinician:'Dr. Michael Adams',location:'North Wing',week:'17 Aug',waiting:510,slots:480,utilisation:79},{specialty:'Dermatology',clinician:'Dr. Rachel Evans',location:'Central Outpatients',week:'24 Aug',waiting:760,slots:820,utilisation:73}]

export default function Capacity(){
  const s=useAppStore();const[view,setView]=useState<View>('By Specialty')
  const data=useMemo(()=>{const key=view==='By Specialty'?'specialty':view==='By Clinician'?'clinician':view==='By Location'?'location':'week';return Object.values(base.reduce<Record<string,{name:string;waiting:number;slots:number;utilisation:number;count:number}>>((a,x)=>{const name=x[key];a[name]??={name,waiting:0,slots:0,utilisation:0,count:0};a[name].waiting+=x.waiting;a[name].slots+=x.slots;a[name].utilisation+=x.utilisation;a[name].count++;return a},{})).map(x=>({...x,utilisation:Math.round(x.utilisation/x.count)}))},[view])
  const clinics=useMemo(()=>[...new Set(s.slots.map(x=>x.clinic))].map(clinic=>{const slots=s.slots.filter(x=>x.clinic===clinic);const appointments=s.appointments.filter(a=>a.clinic===clinic);const capacity=slots.reduce((n,x)=>n+x.capacity,0);const booked=appointments.filter(a=>a.status!=='Cancelled').length;const completed=appointments.filter(a=>a.status==='Completed').length;const noShow=appointments.filter(a=>a.status==='No-show').length;return{clinic,capacity,booked,completed,noShow,unused:Math.max(0,capacity-booked)}}),[s.slots,s.appointments])
  return <><PageHeader title="Capacity Management" subtitle="Understand available slots, utilisation, waiting demand and operational capacity gaps."/>
    <div className="tabs standalone">{(['By Specialty','By Clinician','By Location','By Week'] as View[]).map(x=><button key={x} className={view===x?'active':''} onClick={()=>setView(x)}>{x}</button>)}</div>
    <div className="capacity-kpis">{[['Available slots',s.slots.filter(x=>x.status==='Available').length.toString(),'Published demo slots'],['Booked',s.appointments.filter(x=>!['Cancelled','No-show'].includes(x.status)).length.toString(),'Live appointment records'],['Average utilisation',`${Math.round(data.reduce((n,x)=>n+x.utilisation,0)/Math.max(1,data.length))}%`,'Selected view'],['Capacity gap',data.reduce((n,x)=>n+Math.max(0,x.waiting-x.slots),0).toLocaleString(),'Slots below waiting demand']].map(x=><Card key={x[0]}><span>{x[0]}</span><strong>{x[1]}</strong><small>{x[2]}</small></Card>)}</div>
    <div className="analytics-grid"><Card title={`Capacity vs waiting demand · ${view}`}><ResponsiveContainer width="100%" height={320}><BarChart data={data}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name"/><YAxis/><Tooltip/><Legend/><Bar dataKey="waiting" fill="#3346A8" radius={[4,4,0,0]}/><Bar dataKey="slots" fill="#19A7AE" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></Card><Card className="ai-capacity"><div className="eyebrow"><Sparkles size={14}/> AI capacity insight</div><h2>Cardiology demand exceeds scheduled capacity</h2><p>An additional <strong>86 appointment slots</strong> may help reduce the highest-risk waiting cohort over the next four weeks.</p><div className="recommend"><AlertTriangle/><p>Review weekend clinics and unused cross-site capacity with service leadership.</p></div><small>Operational simulation · Not a validated forecast</small></Card></div>
    <Card title="Clinic utilisation"><div className="capacity-table"><div className="capacity-head"><span>Clinic</span><span>Capacity</span><span>Booked</span><span>Completed</span><span>No-show</span><span>Unused</span></div>{clinics.map(d=><div key={d.clinic}><strong>{d.clinic}</strong><span>{d.capacity}</span><span>{d.booked}</span><span>{d.completed}</span><span><Badge tone={d.noShow?'critical':'success'}>{d.noShow}</Badge></span><span>{d.unused}</span></div>)}</div></Card>
  </>
}
