import { useState } from 'react'
import { ArrowLeft, CheckCircle2, Clipboard, FileText, Pencil, RotateCcw, Send, ShieldCheck, WandSparkles, XCircle } from 'lucide-react'
import { useNavigate, useParams } from 'react-router-dom'
import { toast } from 'sonner'
import { ReferralTimeline } from '../components/ReferralTimeline'
import { Badge, Button, Card, Field, Modal, PageHeader, ReadinessBadge } from '../components/ui'
import { useAppStore } from '../stores/useAppStore'
import type { Priority, Specialty } from '../types/domain'
import { formatDate } from '../utils/domain'

export default function ReferralDetail(){
 const{id}=useParams(),nav=useNavigate(),state=useAppStore(); const r=state.referrals.find(x=>x.id===id),p=state.patients.find(x=>x.id===r?.patientId)
 const[infoOpen,setInfoOpen]=useState(false),[clinicalOpen,setClinicalOpen]=useState(false),[rejectOpen,setRejectOpen]=useState(false),[summaryOpen,setSummaryOpen]=useState(false)
 const[summary,setSummary]=useState(r?.summary??''),[rejectReason,setRejectReason]=useState('Not appropriate for service'),[rejectNotes,setRejectNotes]=useState('')
 const[decision,setDecision]=useState({specialty:r?.aiSpecialty??'Cardiology' as Specialty,urgency:r?.aiUrgency??'Routine' as Priority,route:r?.aiRoute??'',notes:''})
 if(!r||!p)return <Card><p>Referral not found.</p><Button onClick={()=>nav('/referrals')}>Return to inbox</Button></Card>
 const safe=(fn:()=>void,msg:string)=>{try{fn();toast.success(msg)}catch(e){toast.error((e as Error).message)}}
 const regenerated=`${r.reason}. ${r.history}. Investigations: ${r.investigations.join(', ')||'none provided'}. Outstanding information: ${r.missingItems.join(', ')||'none'}.`
 return <><button className="back-link" onClick={()=>nav('/referrals')}><ArrowLeft size={16}/> Back to referral inbox</button><PageHeader title={`${p.name} · ${r.id}`} subtitle={`${r.source} · Received ${formatDate(r.receivedAt)} · Owner ${r.owner}`} actions={<><Badge tone={r.aiUrgency==='Urgent'?'critical':'neutral'}>{r.aiUrgency}</Badge><Badge tone="indigo">{r.status}</Badge></>}/>
 <div className="referral-layout"><Card className="document-panel"><div className="document-toolbar"><span><FileText size={17}/> Original referral document</span><Button variant="ghost" onClick={()=>document.getElementById('source-document')?.scrollIntoView({behavior:'smooth'})}>View source</Button></div><div className="paper" id="source-document"><div className="doc-brand">MEADOWBROOK<br/><span>MEDICAL CENTRE</span></div><p><strong>To:</strong> Westbridge University Hospital</p><p><strong>Patient:</strong> {p.name} · DOB {formatDate(p.dob)} · {p.id}</p><p><strong>Dear Colleague,</strong></p><p>{r.reason}. {r.history}.</p><p><strong>Symptoms:</strong> {r.symptoms.join(', ')}.</p><p><strong>Investigations:</strong> {r.investigations.length?r.investigations.join(', '):'No supporting results attached.'}</p><p><strong>Medication:</strong> {r.medications.length?r.medications.join(', '):'Not provided.'}</p><p>Kind regards,<br/>{r.gp}<br/>{r.practice}</p></div></Card>
 <div className="analysis-panel"><div className="analysis-head"><div><div className="eyebrow"><WandSparkles size={14}/> AI referral analysis</div><h2>Clinical validation workspace</h2></div><Badge tone="ai">{r.aiConfidence}% confidence</Badge></div><div className="oversight"><ShieldCheck size={18}/><p><strong>Human oversight required</strong><br/>AI suggestions support review. A clinician makes the final specialty, urgency and routing decision.</p></div>
 <div className="detail-grid"><Card><span className="label">Patient information</span><h3>{p.name}</h3><p>{p.id} · DOB {formatDate(p.dob)}</p><p>{p.phone}</p></Card><Card><span className="label">Referral source</span><h3>{r.gp}</h3><p>{r.practice}</p><p>{r.source}</p></Card></div>
 <Card className="suggestion-card"><div><span className="label">AI suggested specialty</span><h3>{r.aiSpecialty}</h3><p>{r.aiReason}</p><button className="source-link" onClick={()=>document.getElementById('source-document')?.scrollIntoView({behavior:'smooth'})}>View source · Page 1 · Clinical History</button></div><Badge tone="ai">AI-assisted routing</Badge></Card><Card className="suggestion-card"><div><span className="label">AI suggested urgency</span><h3>{r.aiUrgency}</h3><p>Symptoms described may require expedited review. This is not a final clinical triage decision.</p></div><Badge tone={r.aiUrgency==='Urgent'?'critical':'warning'}>{r.aiUrgency}</Badge></Card>
 <Card><div className="card-head"><div><span className="label">Referral readiness</span><h3><ReadinessBadge readiness={r.readiness}/></h3></div>{r.missingItems.length>0&&<Button variant="secondary" onClick={()=>setInfoOpen(true)}><Send size={15}/> Request information</Button>}</div>{r.missingItems.length?<div className="missing-chips">{r.missingItems.map(i=><Badge key={i} tone="warning">! {i}</Badge>)}</div>:<p>All mandatory information is present. Referral is ready for clinical validation.</p>}{r.receivedItems.length>0&&<p className="received">✓ Received: {r.receivedItems.join(', ')}</p>}</Card>
 <Card title="AI-generated referral summary" action={<div className="summary-tools"><button title="Copy" onClick={()=>{navigator.clipboard?.writeText(r.summary);toast.success('Summary copied')}}><Clipboard size={15}/></button><button title="Edit" onClick={()=>{setSummary(r.summary);setSummaryOpen(true)}}><Pencil size={15}/></button><button title="Regenerate" onClick={()=>safe(()=>state.updateReferralSummary(r.id,regenerated),'Summary regenerated')}><RotateCcw size={15}/></button></div>}><p>{r.summary}</p><small>AI-generated summary · Review against source before clinical use</small></Card>
 {r.duplicateOf&&<Card className="duplicate"><Badge tone="warning">Possible duplicate · High match</Badge><h3>{r.duplicateOf}</h3><p>Same patient · Same specialty · Received 9 days earlier. No records are merged automatically.</p><div><Button variant="secondary" onClick={()=>nav(`/referrals/${r.duplicateOf}`)}>Review existing</Button><Button variant="ghost" onClick={()=>safe(()=>state.keepBothReferrals(r.id),'Both referrals retained with audit history')}>Keep both</Button><Button variant="danger" onClick={()=>safe(()=>state.markDuplicate(r.id,r.duplicateOf!),'Referral marked duplicate')}>Mark duplicate</Button></div></Card>}
 <div className="clinical-actions"><Button variant="danger" disabled={r.status==='Approved'} onClick={()=>setRejectOpen(true)}><XCircle size={16}/> Reject</Button><Button variant="secondary" disabled={r.status==='Approved'} onClick={()=>setClinicalOpen(true)}><Pencil size={16}/> Modify decision</Button><Button disabled={r.status==='Approved'||r.readiness!=='Complete'} onClick={()=>safe(()=>state.approveReferral(r.id),'Referral approved and added to waiting list')}><CheckCircle2 size={16}/> Approve AI suggestion</Button></div>{r.status==='Approved'&&<Card className="approved"><CheckCircle2/><div><strong>Clinical decision recorded</strong><p>Final: {r.finalSpecialty} · {r.finalUrgency} · {r.finalRoute}</p>{(r.finalSpecialty!==r.aiSpecialty||r.finalUrgency!==r.aiUrgency)&&<small>AI suggestion preserved above · Decision modified by {state.role}</small>}</div><Button onClick={()=>nav('/waiting-list')}>Open waiting list</Button></Card>}</div></div>
 <Card title="Referral timeline"><ReferralTimeline events={r.timeline}/></Card>
 <Modal open={infoOpen} onClose={()=>setInfoOpen(false)} title="Request missing information"><div className="modal-body"><Field label="Recipient"><input value={`${r.gp} · ${r.practice}`} readOnly/></Field><Field label="Missing items"><div className="check-list">{r.missingItems.map(i=><label key={i}><input type="checkbox" defaultChecked/> {i}</label>)}</div></Field><Field label="Message preview"><textarea rows={5} readOnly value={`We require the following information before this referral can progress:\n\n- ${r.missingItems.join('\n- ')}`}/></Field><div className="modal-actions"><Button variant="ghost" onClick={()=>setInfoOpen(false)}>Cancel</Button><Button onClick={()=>{safe(()=>state.requestInformation(r.id),'Demo information request sent');setInfoOpen(false)}}>Send demo request</Button></div></div></Modal>
 <Modal open={summaryOpen} onClose={()=>setSummaryOpen(false)} title="Edit referral summary"><div className="modal-body"><Field label="Clinician-reviewed summary"><textarea rows={7} value={summary} onChange={e=>setSummary(e.target.value)}/></Field><div className="modal-actions"><Button variant="ghost" onClick={()=>setSummaryOpen(false)}>Cancel</Button><Button onClick={()=>{safe(()=>state.updateReferralSummary(r.id,summary),'Reviewed summary saved');setSummaryOpen(false)}}>Save summary</Button></div></div></Modal>
 <Modal open={clinicalOpen} onClose={()=>setClinicalOpen(false)} title="Final clinical decision"><div className="modal-body"><div className="ai-reference"><WandSparkles size={16}/><span>AI suggestion</span><strong>{r.aiSpecialty} · {r.aiUrgency} · {r.aiRoute}</strong></div><div className="form-grid"><Field label="Final specialty"><select value={decision.specialty} onChange={e=>setDecision({...decision,specialty:e.target.value as Specialty})}>{['Cardiology','Neurology','Orthopaedics','Gastroenterology','Respiratory','Dermatology'].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Final urgency"><select value={decision.urgency} onChange={e=>setDecision({...decision,urgency:e.target.value as Priority})}>{['Routine','Priority','Urgent','Very Urgent'].map(x=><option key={x}>{x}</option>)}</select></Field></div><Field label="Final route"><input value={decision.route} onChange={e=>setDecision({...decision,route:e.target.value})}/></Field><Field label="Clinical notes"><textarea rows={3} value={decision.notes} onChange={e=>setDecision({...decision,notes:e.target.value})}/></Field><div className="modal-actions"><Button variant="ghost" onClick={()=>setClinicalOpen(false)}>Cancel</Button><Button onClick={()=>{safe(()=>state.approveReferral(r.id,decision),'Clinical decision approved');setClinicalOpen(false)}}>Modify & approve</Button></div></div></Modal>
 <Modal open={rejectOpen} onClose={()=>setRejectOpen(false)} title="Reject referral"><div className="modal-body"><Field label="Reason"><select value={rejectReason} onChange={e=>setRejectReason(e.target.value)}>{['Not appropriate for service','Insufficient information','Duplicate','Alternative service recommended','Other'].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Notes (optional)"><textarea rows={3} value={rejectNotes} onChange={e=>setRejectNotes(e.target.value)}/></Field><div className="modal-actions"><Button variant="ghost" onClick={()=>setRejectOpen(false)}>Cancel</Button><Button variant="danger" onClick={()=>{safe(()=>state.rejectReferral(r.id,`${rejectReason}${rejectNotes?`: ${rejectNotes}`:''}`),'Referral rejected');setRejectOpen(false)}}>Confirm rejection</Button></div></div></Modal></>
}
