import { useEffect, useMemo, useState } from 'react'
import { CheckCircle2, ChevronLeft, ChevronRight, Database, Mail, Network, Plug, RotateCcw, ShieldCheck, Smartphone, TriangleAlert } from 'lucide-react'
import { toast } from 'sonner'
import { CustomSelect, Badge, Button, Card, PageHeader } from '../components/ui'
import { useAppStore } from '../stores/useAppStore'
import { formatDateTime } from '../utils/domain'

export function Integrations(){
 const cards=[[Smartphone,'GP Portal','Demo Connected','Inbound structured referrals'],[Mail,'Secure Email','Simulation','Document referral ingestion'],[Network,'FHIR','Simulation','Patient · ServiceRequest · Appointment'],[Plug,'REST API','Simulation','Referral and scheduling endpoints'],[Database,'EHR','Disabled','Patient context and results'],[Smartphone,'Patient Portal','Demo Connected','Offers and confirmations']] as const
 return <><PageHeader title="Referral Sources & Integrations" subtitle="Simulated connectivity for demonstrating referral orchestration. No live clinical systems are connected."/><div className="integration-notice"><TriangleAlert/> All integrations on this page are demo simulations. SmartReferral AI is not sending or receiving live healthcare data.</div><div className="integration-grid">{cards.map(([Icon,name,status,detail])=><Card key={name}><div className="integration-icon"><Icon size={23}/></div><div><h3>{name}</h3><p>{detail}</p></div><Badge tone={status==='Demo Connected'?'success':status==='Disabled'?'neutral':'warning'}>{status}</Badge><Button variant="ghost" onClick={()=>toast.info(`${name}: ${status}. This connector is a frontend-only simulation with no live endpoint.`)}>View demo configuration</Button></Card>)}</div><Card title="FHIR Demo Mapping"><p className="section-sub">Conceptual mapping only · No live FHIR server</p><div className="fhir-map">{['Patient','ServiceRequest','Appointment','Practitioner','Schedule','Slot','Task','Communication'].map(x=><Badge key={x} tone="indigo">{x}</Badge>)}</div></Card></>
}

export function AuditTrail(){
 const s=useAppStore(); const[q,setQ]=useState(''),[category,setCategory]=useState('All actions'),[page,setPage]=useState(1)
 const rows=useMemo(()=>s.audit.filter(a=>(!q||`${a.user} ${a.referralId} ${a.action}`.toLowerCase().includes(q.toLowerCase()))&&(category==='All actions'||(category==='Clinical decisions'?/approved|rejected|priority/i.test(a.action):/appointment|reminder/i.test(a.action)))),[s.audit,q,category])
 const pageSize=8,pages=Math.max(1,Math.ceil(rows.length/pageSize)),visibleRows=rows.slice((page-1)*pageSize,page*pageSize)
 useEffect(()=>setPage(1),[q,category])
 useEffect(()=>{if(page>pages)setPage(pages)},[page,pages])
 const exportAudit=()=>{const csv=['Time,User,Referral,Action,Previous,New',...rows.map(a=>[a.at,a.user,a.referralId??'',a.action,a.previous??'',a.next??''].map(x=>`"${String(x).replaceAll('"','""')}"`).join(','))].join('\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));const link=document.createElement('a');link.href=url;link.download='smartreferral-demo-audit.csv';link.click();URL.revokeObjectURL(url);toast.success('Demo audit exported')}
 return <><PageHeader title="Audit Trail" subtitle="Trace AI outputs, human decisions and operational state changes across the access journey." actions={<Button variant="secondary" onClick={exportAudit}>Export demo audit</Button>}/><Card><div className="table-tools"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search audit events"/><CustomSelect value={category} onChange={e=>setCategory(e.target.value)}><option>All actions</option><option>Clinical decisions</option><option>Scheduling</option></CustomSelect><span>{rows.length} events</span></div><div className="table-wrap audit-table"><table><thead><tr><th>Time</th><th>User</th><th>Patient</th><th>Referral</th><th>Action</th><th>Previous</th><th>New</th></tr></thead><tbody>{visibleRows.map(a=><tr key={a.id}><td>{formatDateTime(a.at)}</td><td><strong>{a.user}</strong></td><td>{s.patients.find(p=>p.id===a.patientId)?.name??'—'}</td><td><code>{a.referralId??'—'}</code></td><td>{a.action}</td><td>{a.previous??'—'}</td><td>{a.next??'—'}</td></tr>)}</tbody></table></div><div className="pagination"><span>Page {page} of {pages}</span><Button variant="ghost" disabled={page===1} onClick={()=>setPage(page-1)}><ChevronLeft size={15}/> Previous</Button><Button variant="ghost" disabled={page===pages} onClick={()=>setPage(page+1)}>Next <ChevronRight size={15}/></Button></div></Card></>
}

export function SettingsPage(){const s=useAppStore();return <><PageHeader title="Settings" subtitle="Configure this frontend product demonstration and simulated operating context."/><div className="settings-grid"><Card title="Demo Controls"><div className="settings-row"><div><h3>Reset Demo Data</h3><p>Restore the original referrals, waiting list, slots, appointments, messages and audit history.</p></div><Button variant="danger" onClick={()=>{if(confirm('Reset all SmartReferral demo data to its original state?')){s.resetDemo();toast.success('Demo data reset')}}}><RotateCcw size={15}/> Reset Demo Data</Button></div></Card><Card title="Current environment"><div className="detail-list"><div><span>Facility</span><strong>Westbridge University Hospital</strong></div><div><span>Environment</span><Badge tone="warning">Demo only</Badge></div><div><span>Persistence</span><strong>Browser localStorage</strong></div><div><span>Operating date</span><strong>13 August 2026</strong></div></div></Card><Card title="Governance"><div className="governance"><ShieldCheck/><div><strong>Human clinical oversight enabled</strong><p>AI outputs remain suggestions. Clinical approval is limited by simulated role permission.</p></div></div><div className="governance"><CheckCircle2/><div><strong>Synthetic data only</strong><p>All people and organisations in this demo are fictional.</p></div></div></Card></div></>}
