import { create } from 'zustand'
import { persist } from 'zustand/middleware'
import * as seed from '../data/seed'
import type { Appointment, AuditEvent, CancellationOpportunity, Communication, Notification, Patient, Priority, Readiness, Referral, Role, Slot, Specialty, WaitingEntry } from '../types/domain'
import { breachRisk, uid } from '../utils/domain'

const now = () => new Date().toISOString()
const clone = <T,>(value: T): T => JSON.parse(JSON.stringify(value))
const permissionMap: Record<string, Role[]> = {
  intake: ['Referral Administrator','Administrator'], requestInfo: ['Referral Administrator','Clinician','Administrator'], clinical: ['Clinician','Consultant','Administrator'],
  schedule: ['Scheduler','Access Manager','Administrator'], attendance: ['Scheduler','Referral Administrator','Administrator'], analytics: ['Access Manager','Operations Manager','Administrator'],
}
export const can = (role: Role, permission: keyof typeof permissionMap) => permissionMap[permission].includes(role)

interface AppState {
  role: Role; patients: Patient[]; referrals: Referral[]; waitingList: WaitingEntry[]; slots: Slot[]; appointments: Appointment[];
  communications: Communication[]; cancellations: CancellationOpportunity[]; audit: AuditEvent[]; notifications: Notification[];
  setRole: (role: Role) => void; addReferral: (referral: Referral, patient?: Patient) => void;
  requestInformation: (referralId: string) => void; addInformation: (referralId: string, item: string) => void;
  approveReferral: (referralId: string, decision?: { specialty?: Specialty; urgency?: Priority; route?: string; notes?: string }) => void;
  rejectReferral: (referralId: string, reason: string) => void; markDuplicate: (referralId: string, duplicateOf: string) => void;
  keepBothReferrals: (referralId: string) => void; updateReferralSummary: (referralId: string, summary: string) => void;
  updateWaitingPriority: (waitingId: string, priority: Priority) => void;
  assignAppointment: (waitingId: string, slotId: string) => string; bookManual: (patientId: string, referralId: string, slotId: string) => string;
  rescheduleAppointment: (appointmentId: string, slotId: string) => void;
  cancelAppointment: (appointmentId: string) => void; offerCancellation: (opportunityId: string, patientId: string) => void;
  respondCancellation: (opportunityId: string, response: 'Accepted'|'Declined'|'No Response') => void;
  sendReminder: (appointmentId: string, channel: 'SMS'|'Email'|'Portal'|'Phone') => void; confirmPatient: (appointmentId: string) => void;
  failReminder: (appointmentId: string) => void; recordPatientResponse: (appointmentId: string, response: 'Needs Reschedule'|'Cancelled'|'No Response') => void;
  updateAttendance: (appointmentId: string, status: Appointment['status']) => void; returnToWaitingList: (appointmentId: string) => void;
  resetDemo: () => void; markNotificationsRead: () => void;
}

const initial = () => ({ patients: clone(seed.patients), referrals: clone(seed.referrals), waitingList: clone(seed.waitingList), slots: clone(seed.slots), appointments: clone(seed.appointments), communications: clone(seed.communications), cancellations: clone(seed.cancellations), audit: clone(seed.audit), notifications: clone(seed.notifications) })
const auditEvent = (state: AppState, action: string, referralId?: string, previous?: string, next?: string): AuditEvent => ({ id: uid('AUD'), at: now(), user: state.role === 'Clinician' ? 'Dr. Nathan Cole' : state.role === 'Scheduler' ? 'Laura Bennett' : state.role, referralId, patientId: state.referrals.find(r=>r.id===referralId)?.patientId, action, previous, next })

export const useAppStore = create<AppState>()(persist((set, get) => ({
  role: 'Administrator', ...initial(), setRole: role => set({ role }),
  addReferral: (referral, patient) => {const s=get();if(!can(s.role,'intake'))throw Error('Referral intake requires Referral Administrator or Administrator role.');set({ patients: patient ? [...s.patients, patient] : s.patients, referrals: [referral, ...s.referrals], communications:[{id:uid('COM'),patientId:referral.patientId,referralId:referral.id,at:now(),channel:'Portal',type:'Referral received',status:'Sent',message:'Your referral has been received and is being processed.'},...s.communications], audit: [auditEvent(s,'Referral created',referral.id,undefined,referral.status),...s.audit] })},
  requestInformation: referralId => {
    const s=get(); if(!can(s.role,'requestInfo')) throw new Error('Your current role cannot request clinical information.')
    set({ referrals:s.referrals.map(r=>r.id===referralId?{...r,status:'Awaiting Information',timeline:[...r.timeline,{id:uid('TL'),at:now(),label:'Information requested',actor:s.role,detail:r.missingItems.join(', ')}]}:r), communications:[{id:uid('COM'),patientId:s.referrals.find(r=>r.id===referralId)!.patientId,referralId,at:now(),channel:'Email',type:'Missing information request',status:'Sent',message:`Please provide: ${s.referrals.find(r=>r.id===referralId)!.missingItems.join(', ')}`},...s.communications], audit:[auditEvent(s,'Information requested',referralId,'Incomplete','Awaiting Information'),...s.audit] })
  },
  addInformation: (referralId,item) => { const s=get(); const ref=s.referrals.find(r=>r.id===referralId); if(!ref) throw Error('Referral not found.'); const remaining=ref.missingItems.filter(x=>x!==item); const readiness:Readiness=remaining.length?'Incomplete':'Complete'; set({referrals:s.referrals.map(r=>r.id===referralId?{...r,missingItems:remaining,receivedItems:[...r.receivedItems,item],readiness,status:remaining.length?'Awaiting Information':'Needs Review',timeline:[...r.timeline,{id:uid('TL'),at:now(),label:'Information received',actor:s.role,detail:item}]}:r),audit:[auditEvent(s,'Referral information received',referralId,ref.readiness,readiness),...s.audit]}) },
  approveReferral: (referralId,decision={}) => { const s=get(); if(!can(s.role,'clinical')) throw Error('Clinical approval requires Clinician, Consultant or Administrator role.'); const ref=s.referrals.find(r=>r.id===referralId); if(!ref) throw Error('Referral not found.'); if(ref.readiness!=='Complete') throw Error('Missing mandatory information must be resolved before approval.'); if(ref.status==='Rejected') throw Error('A rejected referral cannot be approved.'); if(s.waitingList.some(w=>w.referralId===referralId)) throw Error('This referral already has a waiting-list record.'); const specialty=decision.specialty??ref.aiSpecialty, urgency=decision.urgency??ref.aiUrgency, route=decision.route??ref.aiRoute; const waiting:WaitingEntry={id:uid('WL'),referralId,patientId:ref.patientId,specialty,priority:urgency,waitingSince:now().slice(0,10),targetDays:urgency==='Very Urgent'?7:urgency==='Urgent'?14:urgency==='Priority'?21:28,readiness:'Complete',cancellationReady:true,noShowRisk:'Low',status:'Active'}; set({referrals:s.referrals.map(r=>r.id===referralId?{...r,finalSpecialty:specialty,finalUrgency:urgency,finalRoute:route,clinicianNotes:decision.notes,status:'Approved',timeline:[...r.timeline,{id:uid('TL'),at:now(),label: specialty!==r.aiSpecialty||urgency!==r.aiUrgency?'Clinician modified and approved':'Referral approved',actor:s.role,detail:`${specialty} · ${urgency} · ${route}`},{id:uid('TL'),at:now(),label:'Waiting-list entry created',actor:'SmartReferral AI'}]}:r),waitingList:[waiting,...s.waitingList],communications:[{id:uid('COM'),patientId:ref.patientId,referralId,at:now(),channel:'SMS',type:'Waiting-list confirmation',status:'Sent',message:`Your ${specialty} referral is approved and you have been added to the waiting list.`},...s.communications],audit:[auditEvent(s,'Referral approved',referralId,`${ref.aiSpecialty} · ${ref.aiUrgency}`,`${specialty} · ${urgency}`),...s.audit]}) },
  rejectReferral: (referralId,reason) => {const s=get();if(!can(s.role,'clinical'))throw Error('Clinical role required.');set({referrals:s.referrals.map(r=>r.id===referralId?{...r,status:'Rejected',timeline:[...r.timeline,{id:uid('TL'),at:now(),label:'Referral rejected',actor:s.role,detail:reason}]}:r),audit:[auditEvent(s,'Referral rejected',referralId,undefined,reason),...s.audit]})},
  markDuplicate:(referralId,duplicateOf)=>{const s=get();set({referrals:s.referrals.map(r=>r.id===referralId?{...r,status:'Duplicate',duplicateOf}:r),audit:[auditEvent(s,'Referral marked duplicate',referralId,undefined,duplicateOf),...s.audit]})},
  keepBothReferrals:referralId=>{const s=get();const ref=s.referrals.find(r=>r.id===referralId);if(!ref)throw Error('Referral not found.');set({referrals:s.referrals.map(r=>r.id===referralId?{...r,duplicateOf:undefined,status:r.readiness==='Complete'?'Needs Review':'AI Processed',timeline:[...r.timeline,{id:uid('TL'),at:now(),label:'Duplicate review completed',actor:s.role,detail:'Clinician retained both referrals'}]}:r),audit:[auditEvent(s,'Possible duplicate retained',referralId,ref.duplicateOf,'Keep both'),...s.audit]})},
  updateReferralSummary:(referralId,summary)=>{const s=get();if(!summary.trim())throw Error('Referral summary cannot be empty.');set({referrals:s.referrals.map(r=>r.id===referralId?{...r,summary:summary.trim(),timeline:[...r.timeline,{id:uid('TL'),at:now(),label:'Referral summary updated',actor:s.role}]}:r),audit:[auditEvent(s,'Referral summary updated',referralId),...s.audit]})},
  updateWaitingPriority:(waitingId,priority)=>{const s=get();if(!can(s.role,'clinical'))throw Error('Only a clinical role can change final priority.');const w=s.waitingList.find(x=>x.id===waitingId);if(!w)throw Error('Waiting record not found.');set({waitingList:s.waitingList.map(x=>x.id===waitingId?{...x,priority,targetDays:priority==='Very Urgent'?7:priority==='Urgent'?14:priority==='Priority'?21:28}:x),referrals:s.referrals.map(r=>r.id===w.referralId?{...r,finalUrgency:priority,timeline:[...r.timeline,{id:uid('TL'),at:now(),label:'Waiting priority updated',actor:s.role,detail:`${w.priority} to ${priority}`}]}:r),audit:[auditEvent(s,'Waiting priority updated',w.referralId,w.priority,priority),...s.audit]})},
  assignAppointment:(waitingId,slotId)=>{const s=get();if(!can(s.role,'schedule'))throw Error('Scheduling permission required.');const w=s.waitingList.find(x=>x.id===waitingId),slot=s.slots.find(x=>x.id===slotId);if(!w||!slot)throw Error('Waiting record or slot not found.');if(w.readiness!=='Complete'||w.status!=='Active')throw Error('Patient is not ready for scheduling.');if(slot.status!=='Available'||slot.booked>=slot.capacity)throw Error('This slot is no longer available.');if(slot.specialty!==w.specialty)throw Error('Slot specialty does not match the approved referral.');if(s.appointments.some(a=>a.patientId===w.patientId&&a.date===slot.date&&a.time===slot.start&&!['Cancelled','No-show'].includes(a.status)))throw Error('Patient has a conflicting appointment.');const ref=s.referrals.find(r=>r.id===w.referralId);if(ref?.status==='Rejected')throw Error('Cannot schedule a rejected referral.');const id=uid('APT');const apt:Appointment={id,patientId:w.patientId,referralId:w.referralId,slotId,specialty:w.specialty,practitioner:slot.practitioner,clinic:slot.clinic,date:slot.date,time:slot.start,location:slot.location,status:'Scheduled',noShowRisk:w.noShowRisk,reminderStatus:'Not sent'};set({appointments:[apt,...s.appointments],slots:s.slots.map(x=>x.id===slotId?{...x,booked:x.booked+1,status:'Booked'}:x),waitingList:s.waitingList.map(x=>x.id===waitingId?{...x,status:'Scheduled',suggestedSlotId:slotId}:x),referrals:s.referrals.map(r=>r.id===w.referralId?{...r,timeline:[...r.timeline,{id:uid('TL'),at:now(),label:'Appointment matched',actor:'SmartReferral AI',detail:`Matched to ${slot.clinic}`},{id:uid('TL'),at:now(),label:'Appointment confirmed',actor:s.role,detail:`${slot.date} ${slot.start} · ${slot.practitioner}`}]}:r),communications:[{id:uid('COM'),patientId:w.patientId,referralId:w.referralId,appointmentId:id,at:now(),channel:'SMS',type:'Appointment confirmed',status:'Sent',message:`Your appointment is confirmed for ${slot.date} at ${slot.start}.`},...s.communications],notifications:[{id:uid('NT'),title:'Appointment created',detail:`${slot.specialty} · ${slot.date} ${slot.start}`,at:now(),read:false,severity:'info'},...s.notifications],audit:[auditEvent(s,'Appointment assigned',w.referralId,'Waiting',id),...s.audit]});return id},
  bookManual:(patientId,referralId,slotId)=>{const w=get().waitingList.find(x=>x.patientId===patientId&&x.referralId===referralId);if(!w)throw Error('An active waiting-list record is required.');return get().assignAppointment(w.id,slotId)},
  rescheduleAppointment:(appointmentId,slotId)=>{const s=get();if(!can(s.role,'schedule'))throw Error('Scheduling permission required.');const apt=s.appointments.find(a=>a.id===appointmentId),next=s.slots.find(x=>x.id===slotId);if(!apt||!next)throw Error('Appointment or slot not found.');if(['Cancelled','Completed','No-show'].includes(apt.status))throw Error('This appointment cannot be rescheduled.');if(next.status!=='Available'||next.booked>=next.capacity)throw Error('The replacement slot is no longer available.');if(next.specialty!==apt.specialty)throw Error('Replacement slot specialty does not match.');if(s.appointments.some(a=>a.id!==appointmentId&&a.patientId===apt.patientId&&a.date===next.date&&a.time===next.start&&!['Cancelled','No-show'].includes(a.status)))throw Error('Patient has a conflicting appointment.');const old=apt.slotId;set({appointments:s.appointments.map(a=>a.id===appointmentId?{...a,slotId,date:next.date,time:next.start,practitioner:next.practitioner,clinic:next.clinic,location:next.location,status:'Scheduled',reminderStatus:'Not sent',lastReminder:undefined}:a),slots:s.slots.map(sl=>sl.id===old?{...sl,status:'Available',booked:Math.max(0,sl.booked-1)}:sl.id===slotId?{...sl,status:'Booked',booked:sl.booked+1}:sl),cancellations:[{id:uid('CAN'),slotId:old,appointmentId,createdAt:now(),status:'Open'},...s.cancellations],communications:[{id:uid('COM'),patientId:apt.patientId,referralId:apt.referralId,appointmentId,at:now(),channel:'SMS',type:'Appointment rescheduled',status:'Sent',message:`Your appointment is now ${next.date} at ${next.start}.`},...s.communications],audit:[auditEvent(s,'Appointment rescheduled',apt.referralId,`${apt.date} ${apt.time}`,`${next.date} ${next.start}`),...s.audit]})},
  cancelAppointment:appointmentId=>{const s=get();if(!can(s.role,'schedule'))throw Error('Scheduling permission required.');const apt=s.appointments.find(a=>a.id===appointmentId);if(!apt)throw Error('Appointment not found.');if(apt.status==='Cancelled')throw Error('Appointment is already cancelled.');const op:CancellationOpportunity={id:uid('CAN'),slotId:apt.slotId,appointmentId,createdAt:now(),status:'Open'};set({appointments:s.appointments.map(a=>a.id===appointmentId?{...a,status:'Cancelled'}:a),slots:s.slots.map(sl=>sl.id===apt.slotId?{...sl,status:'Available',booked:0,cancellationAt:now()}:sl),cancellations:[op,...s.cancellations],audit:[auditEvent(s,'Appointment cancelled',apt.referralId,apt.status,'Cancelled; capacity released'),...s.audit]})},
  offerCancellation:(opportunityId,patientId)=>{const s=get();const op=s.cancellations.find(o=>o.id===opportunityId);if(!op||op.status!=='Open')throw Error('Cancellation opportunity is not open.');const expiresAt=new Date(Date.now()+2*60*60*1000).toISOString();set({cancellations:s.cancellations.map(o=>o.id===opportunityId?{...o,status:'Offer Sent',offeredTo:patientId,expiresAt}:o),communications:[{id:uid('COM'),patientId,at:now(),channel:'SMS',type:'Earlier appointment offer',status:'Sent',message:`An earlier appointment is available. Demo offer expires at ${expiresAt}.`},...s.communications]})},
  respondCancellation:(opportunityId,response)=>{const s=get();const op=s.cancellations.find(o=>o.id===opportunityId);if(!op||op.status!=='Offer Sent'||!op.offeredTo)throw Error('No active offer exists.');if(op.expiresAt&&new Date(op.expiresAt).getTime()<Date.now())throw Error('This cancellation offer has expired.');if(response==='Accepted'){const slot=s.slots.find(x=>x.id===op.slotId)!;const w=s.waitingList.find(x=>x.patientId===op.offeredTo&&x.specialty===slot.specialty&&x.status==='Active');if(!w)throw Error('Eligible patient is no longer available.');get().assignAppointment(w.id,slot.id);set(x=>({cancellations:x.cancellations.map(o=>o.id===opportunityId?{...o,status:'Filled',response}:o)}))}else set({cancellations:s.cancellations.map(o=>o.id===opportunityId?{...o,status:response==='Declined'?'Open':'Offer Sent',response,offeredTo:response==='Declined'?undefined:o.offeredTo,expiresAt:response==='Declined'?undefined:o.expiresAt}:o)})},
  sendReminder:(appointmentId,channel)=>{const s=get();const apt=s.appointments.find(a=>a.id===appointmentId);if(!apt)throw Error('Appointment not found.');if(['Cancelled','Completed','No-show'].includes(apt.status))throw Error('A reminder cannot be sent for this appointment.');set({appointments:s.appointments.map(a=>a.id===appointmentId?{...a,reminderStatus:'Sent',lastReminder:now()}:a),communications:[{id:uid('COM'),patientId:apt.patientId,referralId:apt.referralId,appointmentId,at:now(),channel,type:'Appointment reminder',status:'Sent',message:`Reminder: ${apt.clinic} on ${apt.date} at ${apt.time}.`},...s.communications],audit:[auditEvent(s,'Appointment reminder sent',apt.referralId,undefined,channel),...s.audit]})},
  confirmPatient:appointmentId=>{const s=get();const apt=s.appointments.find(a=>a.id===appointmentId);if(!apt)throw Error('Appointment not found.');if(!['Scheduled','Confirmed'].includes(apt.status))throw Error('This appointment cannot be confirmed.');set({appointments:s.appointments.map(a=>a.id===appointmentId?{...a,status:'Confirmed',noShowRisk:'Low'}:a),communications:[{id:uid('COM'),patientId:apt.patientId,referralId:apt.referralId,appointmentId,at:now(),channel:'Phone',type:'Patient confirmation',status:'Received',message:'Patient confirmed attendance.'},...s.communications],audit:[auditEvent(s,'Patient confirmed attendance',apt.referralId,apt.noShowRisk,'Low risk'),...s.audit]})},
  failReminder:appointmentId=>{const s=get();const apt=s.appointments.find(a=>a.id===appointmentId);if(!apt)throw Error('Appointment not found.');set({appointments:s.appointments.map(a=>a.id===appointmentId?{...a,reminderStatus:'Failed'}:a),communications:[{id:uid('COM'),patientId:apt.patientId,referralId:apt.referralId,appointmentId,at:now(),channel:'SMS',type:'Appointment reminder',status:'Failed',message:'Demo delivery failure. Verify contact details and retry using another channel.'},...s.communications],notifications:[{id:uid('NT'),title:'Reminder failed',detail:`${apt.id} requires administrative follow-up`,at:now(),read:false,severity:'warning'},...s.notifications],audit:[auditEvent(s,'Appointment reminder failed',apt.referralId,'Sending','Failed'),...s.audit]})},
  recordPatientResponse:(appointmentId,response)=>{const s=get();const apt=s.appointments.find(a=>a.id===appointmentId);if(!apt)throw Error('Appointment not found.');if(!['Scheduled','Confirmed'].includes(apt.status))throw Error('Patient response cannot be recorded for this appointment.');if(response==='Cancelled'||response==='Needs Reschedule'){get().cancelAppointment(appointmentId);const next=get();set({waitingList:response==='Needs Reschedule'?next.waitingList.map(w=>w.referralId===apt.referralId?{...w,status:'Active',suggestedSlotId:undefined}:w):next.waitingList,communications:[{id:uid('COM'),patientId:apt.patientId,referralId:apt.referralId,appointmentId,at:now(),channel:'Portal',type:'Patient response',status:'Received',message:response==='Needs Reschedule'?'Patient requested rescheduling; the previous slot was released and the patient returned to the active waiting list.':'Patient cancelled the appointment.'},...next.communications],notifications:[{id:uid('NT'),title:response==='Needs Reschedule'?'Reschedule requested':'Appointment cancelled',detail:`${apt.id} · ${response}`,at:now(),read:false,severity:'warning'},...next.notifications]});return}set({appointments:s.appointments.map(a=>a.id===appointmentId?{...a,noShowRisk:'High'}:a),communications:[{id:uid('COM'),patientId:apt.patientId,referralId:apt.referralId,appointmentId,at:now(),channel:'Portal',type:'Patient response',status:'Sent',message:'No response received; additional administrative confirmation suggested.'},...s.communications],notifications:[{id:uid('NT'),title:'No patient response',detail:`${apt.id} · ${response}`,at:now(),read:false,severity:'warning'},...s.notifications],audit:[auditEvent(s,'Patient response recorded',apt.referralId,apt.status,response),...s.audit]})},
  updateAttendance:(appointmentId,status)=>{const s=get();if(!can(s.role,'attendance'))throw Error('Attendance permission required.');const apt=s.appointments.find(a=>a.id===appointmentId);if(!apt)throw Error('Appointment not found.');const allowed:Record<string,string[]>={Scheduled:['Confirmed','Arrived','Cancelled','No-show'],Confirmed:['Arrived','Cancelled','No-show'],Arrived:['In Progress'], 'In Progress':['Completed']};if(!allowed[apt.status]?.includes(status))throw Error(`Cannot move appointment from ${apt.status} to ${status}.`);set({appointments:s.appointments.map(a=>a.id===appointmentId?{...a,status}:a),audit:[auditEvent(s,'Attendance recorded',apt.referralId,apt.status,status),...s.audit]})},
  returnToWaitingList:appointmentId=>{const s=get();const apt=s.appointments.find(a=>a.id===appointmentId);if(!apt||apt.status!=='No-show')throw Error('Only a no-show appointment can be returned to the waiting list.');set({waitingList:s.waitingList.map(w=>w.referralId===apt.referralId?{...w,status:'Active',noShowRisk:'High'}:w),audit:[auditEvent(s,'Patient returned to waiting list',apt.referralId,'No-show','Active waiting'),...s.audit]})},
  resetDemo:()=>set({...initial()}), markNotificationsRead:()=>set(s=>({notifications:s.notifications.map(n=>({...n,read:true}))})),
}),{name:'smartreferral-demo-v1'}))

export const selectPatient = (state:AppState,id:string) => state.patients.find(p=>p.id===id)
export const selectMetrics = (state:AppState) => ({ waiting:8420 + state.waitingList.filter(w=>w.status==='Active').length-4, urgent:612+state.waitingList.filter(w=>w.status==='Active'&&(w.priority==='Urgent'||w.priority==='Very Urgent')).length-1, over18:1104, missing:327+state.referrals.filter(r=>r.readiness==='Incomplete').length-3, cancellationReady:842+state.waitingList.filter(w=>w.status==='Active'&&w.cancellationReady).length-3, highNoShow:296+state.appointments.filter(a=>a.noShowRisk==='High'&&!['Completed','Cancelled'].includes(a.status)).length-1, breach:state.waitingList.filter(w=>w.status==='Active'&&['High','Breached'].includes(breachRisk(w))).length })
