import { beforeEach, describe, expect, it } from 'vitest'
import { useAppStore } from './useAppStore'
import { breachRisk } from '../utils/domain'

/* eslint-disable @typescript-eslint/no-unused-vars */

describe('connected referral-to-attendance workflows',()=>{
  beforeEach(()=>{localStorage.clear();useAppStore.getState().resetDemo();useAppStore.getState().setRole('Administrator')})
  it('recovers missing information then approves into waiting list',()=>{const s=useAppStore.getState();s.requestInformation('REF-2026-0842');s.addInformation('REF-2026-0842','Recent ECG');s.addInformation('REF-2026-0842','Current medication list');useAppStore.getState().approveReferral('REF-2026-0842');const next=useAppStore.getState();expect(next.referrals.find(r=>r.id==='REF-2026-0842')?.status).toBe('Approved');expect(next.waitingList.some(w=>w.referralId==='REF-2026-0842')).toBe(true)})
  it('preserves AI specialty alongside a human override',()=>{const s=useAppStore.getState();s.addInformation('REF-2026-0842','Recent ECG');s.addInformation('REF-2026-0842','Current medication list');useAppStore.getState().approveReferral('REF-2026-0842',{specialty:'Respiratory',urgency:'Priority',route:'Rapid Respiratory Assessment'});const r=useAppStore.getState().referrals.find(x=>x.id==='REF-2026-0842')!;expect(r.aiSpecialty).toBe('Cardiology');expect(r.finalSpecialty).toBe('Respiratory');expect(useAppStore.getState().waitingList.find(w=>w.referralId===r.id)?.specialty).toBe('Respiratory')})
  it('calculates a high risk patient within three days of target',()=>expect(breachRisk(useAppStore.getState().waitingList.find(w=>w.id==='WL-2204')!)).toBe('High'))
  it('assigns appointment and prevents double-booking',()=>{const s=useAppStore.getState();const id=s.assignAppointment('WL-2141','SL-401');expect(useAppStore.getState().appointments.some(a=>a.id===id)).toBe(true);expect(()=>useAppStore.getState().assignAppointment('WL-2133','SL-401')).toThrow(/no longer available/)})
  it('prevents a patient appointment time conflict and records matched timeline',()=>{const s=useAppStore.getState();useAppStore.setState(x=>({appointments:[{...x.appointments[0],id:'APT-CONFLICT',patientId:'PT-10774',date:'2026-08-17',time:'11:00'},...x.appointments]}));expect(()=>useAppStore.getState().assignAppointment('WL-2204','SL-404')).toThrow(/conflicting appointment/);useAppStore.setState(x=>({appointments:x.appointments.filter(a=>a.id!=='APT-CONFLICT')}));useAppStore.getState().assignAppointment('WL-2204','SL-404');expect(useAppStore.getState().referrals.find(r=>r.id==='REF-2026-0836')?.timeline.some(t=>t.label==='Appointment matched')).toBe(true)})
  it('cancels, offers, accepts and fills released capacity',()=>{const s=useAppStore.getState();s.cancelAppointment('APT-3018');let next=useAppStore.getState();const op=next.cancellations[0];expect(next.slots.find(x=>x.id==='SL-406')?.status).toBe('Available');next.offerCancellation(op.id,'PT-10918');useAppStore.getState().respondCancellation(op.id,'Accepted');next=useAppStore.getState();expect(next.cancellations.find(x=>x.id===op.id)?.status).toBe('Filled');expect(next.appointments.some(a=>a.patientId==='PT-10918'&&a.slotId==='SL-406')).toBe(true)})
  it('prevents acceptance of an expired cancellation offer',()=>{const s=useAppStore.getState();s.cancelAppointment('APT-3018');const op=useAppStore.getState().cancellations[0];useAppStore.getState().offerCancellation(op.id,'PT-10918');useAppStore.setState(x=>({cancellations:x.cancellations.map(c=>c.id===op.id?{...c,expiresAt:'2020-01-01T00:00:00.000Z'}:c)}));expect(()=>useAppStore.getState().respondCancellation(op.id,'Accepted')).toThrow(/expired/)})
  it('sends reminder and completes valid attendance transitions',()=>{const s=useAppStore.getState();s.sendReminder('APT-3018','SMS');s.updateAttendance('APT-3018','Confirmed');s.updateAttendance('APT-3018','Arrived');s.updateAttendance('APT-3018','In Progress');s.updateAttendance('APT-3018','Completed');expect(useAppStore.getState().appointments.find(a=>a.id==='APT-3018')?.status).toBe('Completed');expect(useAppStore.getState().communications[0].type).toBe('Appointment reminder')})
  it('reschedules while releasing original capacity as an opportunity',()=>{const s=useAppStore.getState();s.rescheduleAppointment('APT-3018','SL-401');const next=useAppStore.getState();expect(next.appointments.find(a=>a.id==='APT-3018')?.slotId).toBe('SL-401');expect(next.slots.find(x=>x.id==='SL-406')?.status).toBe('Available');expect(next.cancellations.some(x=>x.slotId==='SL-406')).toBe(true)})
  it('patient confirmation lowers high no-show risk without denying care',()=>{useAppStore.getState().confirmPatient('APT-3018');const apt=useAppStore.getState().appointments.find(a=>a.id==='APT-3018');expect(apt?.status).toBe('Confirmed');expect(apt?.noShowRisk).toBe('Low')})
  it('records no response as high risk and creates follow-up history',()=>{useAppStore.getState().recordPatientResponse('APT-3018','No Response');const next=useAppStore.getState();expect(next.appointments.find(a=>a.id==='APT-3018')?.noShowRisk).toBe('High');expect(next.communications[0].message).toMatch(/No response/)})
  it('releases capacity and returns a reschedule request to active waiting',()=>{useAppStore.getState().recordPatientResponse('APT-3018','Needs Reschedule');const next=useAppStore.getState();expect(next.appointments.find(a=>a.id==='APT-3018')?.status).toBe('Cancelled');expect(next.waitingList.find(w=>w.referralId==='REF-2026-0682')?.status).toBe('Active');expect(next.cancellations.some(c=>c.slotId==='SL-406')).toBe(true)})
  it('records reminder failure with notification and supports retry',()=>{useAppStore.getState().failReminder('APT-3018');expect(useAppStore.getState().appointments.find(a=>a.id==='APT-3018')?.reminderStatus).toBe('Failed');useAppStore.getState().sendReminder('APT-3018','Email');expect(useAppStore.getState().appointments.find(a=>a.id==='APT-3018')?.reminderStatus).toBe('Sent')})
  it('enforces clinician permission when updating waiting priority',()=>{useAppStore.getState().setRole('Scheduler');expect(()=>useAppStore.getState().updateWaitingPriority('WL-2204','Urgent')).toThrow(/clinical role/);useAppStore.getState().setRole('Clinician');useAppStore.getState().updateWaitingPriority('WL-2204','Urgent');expect(useAppStore.getState().waitingList.find(w=>w.id==='WL-2204')?.targetDays).toBe(14)})
  it('updates referral summaries with an audit event',()=>{useAppStore.getState().updateReferralSummary('REF-2026-0842','Clinician reviewed summary.');expect(useAppStore.getState().referrals.find(r=>r.id==='REF-2026-0842')?.summary).toBe('Clinician reviewed summary.');expect(useAppStore.getState().audit[0].action).toBe('Referral summary updated')})
  it('reset restores original demo data',()=>{useAppStore.getState().cancelAppointment('APT-3018');useAppStore.getState().resetDemo();expect(useAppStore.getState().appointments.find(a=>a.id==='APT-3018')?.status).toBe('Scheduled');expect(useAppStore.getState().cancellations).toHaveLength(0)})
})
