import { Children, isValidElement, useEffect, useRef, useState, type ButtonHTMLAttributes, type ChangeEvent, type ReactElement, type ReactNode, type SelectHTMLAttributes } from 'react'
import { Check, ChevronDown, X } from 'lucide-react'
import type { Readiness, Risk } from '../types/domain'

export const Button=({variant='primary',className='',type='button',...props}:ButtonHTMLAttributes<HTMLButtonElement>&{variant?:'primary'|'secondary'|'ghost'|'danger'})=><button type={type} className={`button ${variant} ${className}`} {...props}/>
export const Badge=({children,tone='neutral',title}:{children:ReactNode;tone?:string;title?:string})=><span className={`badge ${tone}`} title={title}>{children}</span>
export const RiskBadge=({risk}:{risk:Risk})=><Badge tone={risk==='Low'?'success':risk==='Medium'?'warning':'critical'} title="Deterministic operational indicator based on wait against target; not a validated clinical model.">● {risk}</Badge>
export const ReadinessBadge=({readiness}:{readiness:Readiness})=><Badge tone={readiness==='Complete'?'success':'warning'} title="Whether mandatory referral information is ready for clinical review.">{readiness==='Complete'?'✓':'!'} {readiness}</Badge>
export const Card=({children,className='',title,action}:{children:ReactNode;className?:string;title?:string;action?:ReactNode})=><section className={`card ${className}`}>{title&&<div className="card-head"><h2>{title}</h2>{action}</div>}{children}</section>
export const Empty=({title,detail}:{title:string;detail:string})=><div className="empty" role="status"><div className="empty-icon">✓</div><strong>{title}</strong><p>{detail}</p></div>

function useDialog(open:boolean,onClose:()=>void){const ref=useRef<HTMLElement>(null);useEffect(()=>{if(!open)return;const previous=document.activeElement as HTMLElement|null,timer=setTimeout(()=>ref.current?.querySelector<HTMLElement>('button,input,select,textarea,[tabindex]:not([tabindex="-1"])')?.focus(),0);const key=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose();if(e.key==='Tab'&&ref.current){const items=[...ref.current.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea:not(:disabled),[tabindex]:not([tabindex="-1"])')];if(!items.length)return;const first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}};document.addEventListener('keydown',key);document.body.style.overflow='hidden';return()=>{clearTimeout(timer);document.removeEventListener('keydown',key);document.body.style.overflow='';previous?.focus()}},[open,onClose]);return ref}
export function Modal({open,onClose,title,children,wide=false}:{open:boolean;onClose:()=>void;title:string;children:ReactNode;wide?:boolean}){const ref=useDialog(open,onClose);return open?<div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()} role="presentation"><section ref={ref} className={`modal ${wide?'wide':''}`} role="dialog" aria-modal="true" aria-labelledby="modal-title"><div className="modal-head"><h2 id="modal-title">{title}</h2><button className="icon-button" onClick={onClose} aria-label="Close dialog"><X size={18}/></button></div>{children}</section></div>:null}
export function Drawer({open,onClose,title,children}:{open:boolean;onClose:()=>void;title:string;children:ReactNode}){const ref=useDialog(open,onClose);return open?<div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()} role="presentation"><aside ref={ref} className="drawer" role="dialog" aria-modal="true" aria-labelledby="drawer-title"><div className="modal-head"><h2 id="drawer-title">{title}</h2><button className="icon-button" onClick={onClose} aria-label="Close drawer"><X size={18}/></button></div>{children}</aside></div>:null}
export const Field=({label,children,hint}:{label:string;children:ReactNode;hint?:string})=><label className="field"><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>
export const PageHeader=({title,subtitle,actions}:{title:string;subtitle:string;actions?:ReactNode})=><header className="page-header"><div><h1>{title}</h1><p>{subtitle}</p></div>{actions&&<div className="page-actions">{actions}</div>}</header>
export const Skeleton=({rows=3}:{rows?:number})=><div className="skeleton" role="status" aria-label="Loading">{Array.from({length:rows},(_,i)=><i key={i}/>)}</div>

type OptionProps={value?:string;children?:ReactNode;disabled?:boolean}
export function CustomSelect({children,value,defaultValue,onChange,disabled,name,'aria-label':ariaLabel,className=''}:Omit<SelectHTMLAttributes<HTMLSelectElement>,'multiple'|'size'>){
 const options=Children.toArray(children).filter(isValidElement).map(node=>{const option=node as ReactElement<OptionProps>;return{value:String(option.props.value??option.props.children??''),label:option.props.children,disabled:option.props.disabled}})
 const controlled=value!==undefined,[internal,setInternal]=useState(String(defaultValue??options[0]?.value??'')),selected=String(controlled?value:internal),[open,setOpen]=useState(false),ref=useRef<HTMLDivElement>(null)
 useEffect(()=>{const close=(event:MouseEvent)=>{if(!ref.current?.contains(event.target as Node))setOpen(false)};document.addEventListener('mousedown',close);return()=>document.removeEventListener('mousedown',close)},[])
 const choose=(next:string)=>{const event={target:{value:next,name}} as unknown as ChangeEvent<HTMLSelectElement>;onChange?.(event);if(!controlled)setInternal(String(event.target.value));setOpen(false)}
 const move=(direction:number)=>{const enabled=options.filter(x=>!x.disabled);const index=enabled.findIndex(x=>x.value===selected);choose(enabled[(index+direction+enabled.length)%enabled.length]?.value??selected)}
 const current=options.find(x=>x.value===selected)
 return <div ref={ref} data-label={ariaLabel} className={`custom-select ${open?'open':''} ${disabled?'disabled':''} ${className}`}>
  <button type="button" className="custom-select-trigger" aria-label={ariaLabel} aria-haspopup="listbox" aria-expanded={open} disabled={disabled} onClick={()=>setOpen(x=>!x)} onKeyDown={e=>{if(e.key==='ArrowDown'){e.preventDefault();move(1)}if(e.key==='ArrowUp'){e.preventDefault();move(-1)}if(e.key==='Escape')setOpen(false)}}><span>{current?.label??'Select'}</span><ChevronDown size={15}/></button>
  {open&&<div className="custom-select-menu" role="listbox" aria-label={ariaLabel}>{options.map(option=><button type="button" role="option" aria-selected={option.value===selected} disabled={option.disabled} className={option.value===selected?'selected':''} key={option.value} onClick={()=>choose(option.value)}><span>{option.label}</span>{option.value===selected&&<Check size={14}/>}</button>)}</div>}
 </div>
}
