import { useEffect, useRef, type ButtonHTMLAttributes, type ReactNode } from 'react'
import { X } from 'lucide-react'
import type { Readiness, Risk } from '../types/domain'

export const Button=({variant='primary',className='',type='button',...props}:ButtonHTMLAttributes<HTMLButtonElement>&{variant?:'primary'|'secondary'|'ghost'|'danger'})=><button type={type} className={`button ${variant} ${className}`} {...props}/>
export const Badge=({children,tone='neutral',title}:{children:ReactNode;tone?:string;title?:string})=><span className={`badge ${tone}`} title={title}>{children}</span>
export const RiskBadge=({risk}:{risk:Risk})=><Badge tone={risk==='Low'?'success':risk==='Medium'?'warning':'critical'} title="Deterministic operational indicator based on wait against target; not a validated clinical model.">● {risk}</Badge>
export const ReadinessBadge=({readiness}:{readiness:Readiness})=><Badge tone={readiness==='Complete'?'success':'warning'} title="Whether mandatory referral information is ready for clinical review.">{readiness==='Complete'?'✓':'!'} {readiness}</Badge>
export const Card=({children,className='',title,action}:{children:ReactNode;className?:string;title?:string;action?:ReactNode})=><section className={`card ${className}`}>{title&&<div className="card-head"><h2>{title}</h2>{action}</div>}{children}</section>
export const Empty=({title,detail}:{title:string;detail:string})=><div className="empty" role="status"><div className="empty-icon">✓</div><strong>{title}</strong><p>{detail}</p></div>

function useDialog(open:boolean,onClose:()=>void){const ref=useRef<HTMLElement>(null);useEffect(()=>{if(!open)return;const previous=document.activeElement as HTMLElement|null,timer=setTimeout(()=>ref.current?.querySelector<HTMLElement>('button,input,select,textarea,[tabindex]:not([tabindex="-1"])')?.focus(),0);const key=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose();if(e.key==='Tab'&&ref.current){const items=[...ref.current.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea:not(:disabled),[tabindex]:not([tabindex="-1"])')];if(!items.length)return;const first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}};document.addEventListener('keydown',key);document.body.style.overflow='hidden';return()=>{clearTimeout(timer);document.removeEventListener('keydown',key);document.body.style.overflow='';previous?.focus()}},[open,onClose]);return ref}
export function Modal({open,onClose,title,children,wide=false}:{open:boolean;onClose:()=>void;title:string;children:ReactNode;wide?:boolean}){const ref=useDialog(open,onClose);return open?<div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()} role="presentation"><section ref={ref} className={`modal ${wide?'wide':''}`} role="dialog" aria-modal="true" aria-labelledby="modal-title"><div className="modal-head"><h2 id="modal-title">{title}</h2><button className="icon-button" onClick={onClose} aria-label="Close dialog"><X size={18}/></button></div>{children}</section></div>:null}
export function Drawer({open,onClose,title,children}:{open:boolean;onClose:()=>void;title:string;children:ReactNode}){const ref=useDialog(open,onClose);return open?<div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()} role="presentation"><aside ref={ref} className="drawer" role="dialog" aria-modal="true" aria-labelledby="drawer-title"><div className="modal-head"><h2 id="drawer-title">{title}</h2><button className="icon-button" onClick={onClose} aria-label="Close drawer"><X size={18}/></button></div>{children}</aside></div>:null}
export const Field=({label,children,hint}:{label:string;children:ReactNode;hint?:string})=><label className="field"><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>
export const PageHeader=({title,subtitle,actions}:{title:string;subtitle:string;actions?:ReactNode})=><header className="page-header"><div><h1>{title}</h1><p>{subtitle}</p></div>{actions&&<div className="page-actions">{actions}</div>}</header>
export const Skeleton=({rows=3}:{rows?:number})=><div className="skeleton" role="status" aria-label="Loading">{Array.from({length:rows},(_,i)=><i key={i}/>)}</div>
